# Generated by Django 3.0.2 on 2020-02-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked_count',
            new_name='down_vote_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='shared_count',
            new_name='up_vote_count',
        ),
        migrations.AlterField(
            model_name='actiononpost',
            name='action',
            field=models.CharField(choices=[('UP_VOTE', 'Up Vote'), ('DOWN_VOTE', 'Down Vote')], max_length=10),
        ),
    ]
