# Generated by Django 3.0.2 on 2020-01-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channeladmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='admins',
        ),
    ]
